services:
  transcoder:
    build:
      context: .
      dockerfile: transcoder.Dockerfile
    ports:
    - "5270:5270"
    networks:
      - srt_network
    volumes:
      - hls-streams-volume:/app/streams
    env_file: ".env"

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - srt_network
    volumes:
      - hls-streams-volume:/app/streams
    env_file: ".env"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - srt_network
    volumes:
      - redis-users-volume:/data

volumes:
  hls-streams-volume:
  redis-users-volume:

networks:
  srt_network:
    name: srt_network
    external: true
